# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.DateField(default='1998-03-03'),
            preserve_default=False,
        ),
    ]
