# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landr_app', '0001_initial'),
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quote_creator', to='landr_app.User'),
            preserve_default=False,
        ),
    ]
