# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landr_app', '0001_initial'),
        ('second_app', '0002_quote_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='quotes_favorited', to='landr_app.User'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_favorite', to='landr_app.User'),
        ),
    ]
