# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_auto_20180323_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='users',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
